project(KubeGraphics)

find_package(Vulkan REQUIRED)
find_package(SDL2 REQUIRED)

get_filename_component(KubeGraphicsDir ${CMAKE_CURRENT_LIST_FILE} PATH)

set(KubeGraphicsSources
    ${KubeGraphicsDir}/BackendWindow.hpp
    ${KubeGraphicsDir}/Buffer.cpp
    ${KubeGraphicsDir}/Buffer.hpp
    ${KubeGraphicsDir}/BufferModel.hpp
    ${KubeGraphicsDir}/BufferModel.ipp
    ${KubeGraphicsDir}/ColorBlendAttachement.hpp
    ${KubeGraphicsDir}/ColorBlendModel.hpp
    ${KubeGraphicsDir}/CommandDispatcher.cpp
    ${KubeGraphicsDir}/CommandDispatcher.hpp
    ${KubeGraphicsDir}/CommandDispatcher.ipp
    ${KubeGraphicsDir}/CommandPool.cpp
    ${KubeGraphicsDir}/CommandPool.hpp
    ${KubeGraphicsDir}/CommandPool.ipp
    ${KubeGraphicsDir}/CommandPoolManager.cpp
    ${KubeGraphicsDir}/CommandPoolManager.hpp
    ${KubeGraphicsDir}/CommandPoolManager.ipp
    ${KubeGraphicsDir}/CommandRecorder.hpp
    ${KubeGraphicsDir}/DepthStencilModel.hpp
    ${KubeGraphicsDir}/DescriptorPool.cpp
    ${KubeGraphicsDir}/DescriptorPool.hpp
    ${KubeGraphicsDir}/DescriptorPoolModel.hpp
    ${KubeGraphicsDir}/DescriptorPoolSize.hpp
    ${KubeGraphicsDir}/DescriptorSetCopyModel.hpp
    ${KubeGraphicsDir}/DescriptorSetLayout.cpp
    ${KubeGraphicsDir}/DescriptorSetLayout.hpp
    ${KubeGraphicsDir}/DescriptorSetLayout.ipp
    ${KubeGraphicsDir}/DescriptorSetLayoutBinding.hpp
    ${KubeGraphicsDir}/DescriptorSetLayoutBinding.ipp
    ${KubeGraphicsDir}/DescriptorSetLayoutModel.hpp
    ${KubeGraphicsDir}/DescriptorSetUpdate.cpp
    ${KubeGraphicsDir}/DescriptorSetUpdate.hpp
    ${KubeGraphicsDir}/DescriptorSetWriteModel.hpp
    ${KubeGraphicsDir}/DynamicStateModel.hpp
    ${KubeGraphicsDir}/Event.cpp
    ${KubeGraphicsDir}/Event.hpp
    ${KubeGraphicsDir}/Fence.cpp
    ${KubeGraphicsDir}/Fence.hpp
    ${KubeGraphicsDir}/Framebuffer.cpp
    ${KubeGraphicsDir}/Framebuffer.hpp
    ${KubeGraphicsDir}/FramebufferManager.cpp
    ${KubeGraphicsDir}/FramebufferManager.hpp
    ${KubeGraphicsDir}/FramebufferManager.ipp
    ${KubeGraphicsDir}/FramebufferModel.hpp
    ${KubeGraphicsDir}/Graphics.cmake
    ${KubeGraphicsDir}/Image.cpp
    ${KubeGraphicsDir}/Image.hpp
    ${KubeGraphicsDir}/ImageModel.hpp
    ${KubeGraphicsDir}/ImageView.cpp
    ${KubeGraphicsDir}/ImageView.hpp
    ${KubeGraphicsDir}/ImageViewModel.hpp
    ${KubeGraphicsDir}/InputAssemblyModel.hpp
    ${KubeGraphicsDir}/Instance.cpp
    ${KubeGraphicsDir}/Instance.hpp
    ${KubeGraphicsDir}/LICENSE
    ${KubeGraphicsDir}/LogicalDevice.cpp
    ${KubeGraphicsDir}/LogicalDevice.hpp
    ${KubeGraphicsDir}/Matrixes.hpp
    ${KubeGraphicsDir}/MemoryAllocation.hpp
    ${KubeGraphicsDir}/MemoryAllocation.cpp
    ${KubeGraphicsDir}/MemoryAllocation.ipp
    ${KubeGraphicsDir}/MemoryAllocationModel.hpp
    ${KubeGraphicsDir}/MemoryAllocationModel.ipp
    ${KubeGraphicsDir}/MemoryAllocator.cpp
    ${KubeGraphicsDir}/MemoryAllocator.hpp
    ${KubeGraphicsDir}/MemoryAllocator.ipp
    ${KubeGraphicsDir}/MultisampleModel.hpp
    ${KubeGraphicsDir}/PerFrameCache.hpp
    ${KubeGraphicsDir}/PhysicalDevice.cpp
    ${KubeGraphicsDir}/PhysicalDevice.hpp
    ${KubeGraphicsDir}/Pipeline.cpp
    ${KubeGraphicsDir}/Pipeline.hpp
    ${KubeGraphicsDir}/PipelineLayout.cpp
    ${KubeGraphicsDir}/PipelineLayout.hpp
    ${KubeGraphicsDir}/PipelineLayoutModel.hpp
    ${KubeGraphicsDir}/PipelineModel.hpp
    ${KubeGraphicsDir}/QueueManager.cpp
    ${KubeGraphicsDir}/QueueManager.hpp
    ${KubeGraphicsDir}/RasterizationModel.hpp
    ${KubeGraphicsDir}/Renderer.cpp
    ${KubeGraphicsDir}/Renderer.hpp
    ${KubeGraphicsDir}/Renderer.ipp
    ${KubeGraphicsDir}/RendererObject.cpp
    ${KubeGraphicsDir}/RendererObject.hpp
    ${KubeGraphicsDir}/RenderPass.cpp
    ${KubeGraphicsDir}/RenderPass.hpp
    ${KubeGraphicsDir}/RenderPass.ipp
    ${KubeGraphicsDir}/RenderPassBeginInfo.hpp
    ${KubeGraphicsDir}/Sampler.cpp
    ${KubeGraphicsDir}/Sampler.hpp
    ${KubeGraphicsDir}/SamplerModel.hpp
    ${KubeGraphicsDir}/Semaphore.cpp
    ${KubeGraphicsDir}/Semaphore.hpp
    ${KubeGraphicsDir}/Shader.cpp
    ${KubeGraphicsDir}/Shader.hpp
    ${KubeGraphicsDir}/ShaderStageModel.hpp
    ${KubeGraphicsDir}/StencilOpState.hpp
    ${KubeGraphicsDir}/SubmitInfo.hpp
    ${KubeGraphicsDir}/Surface.cpp
    ${KubeGraphicsDir}/Surface.hpp
    ${KubeGraphicsDir}/Swapchain.cpp
    ${KubeGraphicsDir}/Swapchain.hpp
    ${KubeGraphicsDir}/Swapchain.ipp
    ${KubeGraphicsDir}/TessellationModel.hpp
    ${KubeGraphicsDir}/VertexInputAttribute.hpp
    ${KubeGraphicsDir}/VertexInputBinding.hpp
    ${KubeGraphicsDir}/VertexInputModel.hpp
    ${KubeGraphicsDir}/ViewportModel.hpp
    ${KubeGraphicsDir}/Vulkan.cpp
    ${KubeGraphicsDir}/Vulkan.hpp
    ${KubeGraphicsDir}/VulkanEnums.hpp
    ${KubeGraphicsDir}/VulkanFlags.hpp
    ${KubeGraphicsDir}/VulkanHandle.hpp
)

add_library(${PROJECT_NAME} ${KubeGraphicsSources})

target_link_libraries(${PROJECT_NAME}
PUBLIC
    KubeCore
    Vulkan::Vulkan
    VulkanMemoryAllocator
    # glm
    SDL2
)

target_include_directories(${PROJECT_NAME}
PUBLIC
    ${SDL2_INCLUDE_DIRS}
)

if(${KF_TESTS})
    include(${KubeGraphicsDir}/Tests/GraphicsTests.cmake)
endif()

if(${KF_BENCHMARKS})
    include(${KubeGraphicsDir}/Benchmarks/GraphicsBenchmarks.cmake)
endif()